# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/wly/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),wly)

$(call add-radio-file-sha1-checked,radio/abl.img,550d88b39425d75109dea33b94ecb679c6906f21)
$(call add-radio-file-sha1-checked,radio/aop.img,ff431a1f311c45298eb8e02612a2cd282d1434ec)
$(call add-radio-file-sha1-checked,radio/aop_config.img,62965fc1a2155279cce28225bff5ec9cf4936bab)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,c8c60529cb53265fc168632672b9de65f902e9f9)
$(call add-radio-file-sha1-checked,radio/cpucp.img,f5ecc5c1b7d38cf38a3f5bc441cfbbfd408d67c3)
$(call add-radio-file-sha1-checked,radio/devcfg.img,2a1bd130e3afe142ee6f7b3bc663d22b953ab5a0)
$(call add-radio-file-sha1-checked,radio/dsp.img,e9f84bc1929d77e5bcf2c8b184bfaed6c7942afb)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,13f5f33df779408b04cdfb3d78dd1ebbd3afb7b4)
$(call add-radio-file-sha1-checked,radio/featenabler.img,e882a0ef2bdf178b5c440f387cfcefb2b3c8383a)
$(call add-radio-file-sha1-checked,radio/hyp.img,575bac39d05c635098fba0af65e21f1aa8bee384)
$(call add-radio-file-sha1-checked,radio/imagefv.img,3962e18e4a812ae5775f183cd65fb52d9278cc12)
$(call add-radio-file-sha1-checked,radio/keymaster.img,8adec30298a650e1a11d97f00e99876aea436031)
$(call add-radio-file-sha1-checked,radio/modem.img,8aa4900a7f58e908c2b16806484b55a35256b426)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,903e1685b64a523d629ac41fce6191b472b8a6e0)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,3b0b388eba9177afd8aa7d7bd0421a14b892b330)
$(call add-radio-file-sha1-checked,radio/qupfw.img,aa10a7e303b3fb39bdfe36ccb2300646cc414d4d)
$(call add-radio-file-sha1-checked,radio/shrm.img,fc42b9c788df54aa9de6124283bd1285feab76df)
$(call add-radio-file-sha1-checked,radio/splash.img,8877705066051214763727acd252d62aba94aa5e)
$(call add-radio-file-sha1-checked,radio/tz.img,e6071deec4448036502825105f04809e75952b67)
$(call add-radio-file-sha1-checked,radio/uefi.img,3ce2282c23e7faac6f7d6ba31630fe067ff79a4e)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,13f04c573deba26392655f7d98bac3a6a96c5209)
$(call add-radio-file-sha1-checked,radio/xbl.img,659ba57d4378e94d817f410a2e4507c75b8ce75a)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,a049847798a139525db7b872861da9254b9ecdcc)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,4694d133e6a761c4a7272a7eb6433045ce691f3a)

endif
