# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/oneplus/wly/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),wly)

$(call add-radio-file-sha1-checked,radio/abl.img,5e85268e36b35ad6430efa7dd63c8c4664e2d1c3)
$(call add-radio-file-sha1-checked,radio/aop.img,6b89d898c180ef4a3ba0bc0a5badcd3bc6d40859)
$(call add-radio-file-sha1-checked,radio/aop_config.img,24e71830225ea4b1692fd08b6a2bab000df72440)
$(call add-radio-file-sha1-checked,radio/bluetooth.img,cc1810c26e173c005c15f755572c743485a17fd6)
$(call add-radio-file-sha1-checked,radio/cpucp.img,e03bf89b7e2d07231f9c3cf66a4fd1d189c10ce5)
$(call add-radio-file-sha1-checked,radio/devcfg.img,86416191b00e317eebd47be6f267e831941f77ce)
$(call add-radio-file-sha1-checked,radio/dsp.img,e9f84bc1929d77e5bcf2c8b184bfaed6c7942afb)
$(call add-radio-file-sha1-checked,radio/engineering_cdt.img,9b3ff45d7d277b518bc68e02825134d6ff379d86)
$(call add-radio-file-sha1-checked,radio/featenabler.img,56c87eb3bc3ca3b73cb3e37763b523a0b549a5ee)
$(call add-radio-file-sha1-checked,radio/hyp.img,f578ec68631724bd1115ede4f9e8fa89c3f749ef)
$(call add-radio-file-sha1-checked,radio/imagefv.img,40d74cf8fcb6ea09841a62fa0fbcac43e6644b95)
$(call add-radio-file-sha1-checked,radio/keymaster.img,45f34b0fca7818b6c7eb3ee177fa4343c87dd8d2)
$(call add-radio-file-sha1-checked,radio/modem.img,548911a750599648a050f527773b68a14eae1ce7)
$(call add-radio-file-sha1-checked,radio/oplus_sec.img,903e1685b64a523d629ac41fce6191b472b8a6e0)
$(call add-radio-file-sha1-checked,radio/oplusstanvbk.img,bd47045448f9deeaa2458d8be74cb4c327fcdd9d)
$(call add-radio-file-sha1-checked,radio/qupfw.img,a453c5c489136ede75274b0e0fc8609dbe9f6bb4)
$(call add-radio-file-sha1-checked,radio/shrm.img,6ca5e1fae8509ba0988f3529cb26b652a23f3418)
$(call add-radio-file-sha1-checked,radio/splash.img,8877705066051214763727acd252d62aba94aa5e)
$(call add-radio-file-sha1-checked,radio/tz.img,6e4cccf67f8162cd89d9042f2d175fd4feb11550)
$(call add-radio-file-sha1-checked,radio/uefi.img,92ff06647f8465e6f3b94709322c3dde823358f7)
$(call add-radio-file-sha1-checked,radio/uefisecapp.img,bd3073b550acabbb7c788cc5cd38004a7d62cd21)
$(call add-radio-file-sha1-checked,radio/xbl.img,0fb9d6052547240895608cc27f78f69dc83b337d)
$(call add-radio-file-sha1-checked,radio/xbl_config.img,3b83ba580ff4a0d8ad77ec84b1db7b331795a3a9)
$(call add-radio-file-sha1-checked,radio/xbl_ramdump.img,78783a350c9839feb85c71d16de203a347436fa9)

endif
